### ISSUE TITLE
ServerRequestIntegrationTest should extend RequestIntegrationTest

### ISSUE THREAD

**Issue by IngeniozIT** [php-http/psr7-integration-tests#57]
**Description**
In the PSR, `ServerRequestInterface` extends `RequestInterface`.
This means that a Server Request implementation should also behave like a `RequestInterface`.

Given the current structure of the tests, it is not easy to verify this.
`RequestIntegrationTest` and `ServerRequestIntegrationTest` both extend `BaseTest`.
In order to check if a Server Request behaves like both a Server Request and a Request, we currently need to create 2 test classes:
- one that extends `ServerRequestIntegrationTest`
- one that extends `RequestIntegrationTest`

**Additional context**

One way to fix this is to make `ServerRequestIntegrationTest` extend `RequestIntegrationTest`.
This will make sure that no Server Request implementations break the behaviours inherited from Request.
However, this will increase the number of tests that validate those implementations and it might create failing tests for implementations that break behaviours inherited from Request.

**Comment by dbu** [comment]
fixed in #58
