### ISSUE TITLE
Release PHPUnit 10 Support

### ISSUE THREAD

**Issue by gsteel** [php-http/psr7-integration-tests#76]
**Description**

It looks like PHPUnit 10 support has been merged into 1.x but has not yet been released

Is there anything I can do to help get this over the line?

**Comment by dbu** [comment]
thanks for the reminder - i did not realize i forgot to release. here you go: https://github.com/php-http/psr7-integration-tests/releases/tag/1.4.0

**Comment by gsteel** [comment]
Legend! Thanks @dbu :)
